export const SHORT_TERM_ENTRY_THRESHOLD_SCORE = 60;

export const SHORT_TERM_STOP_LOSS_PERCENT = -2;
export const SHORT_TERM_TAKE_PROFIT_1_PERCENT = 1.5;
export const SHORT_TERM_TAKE_PROFIT_2_PERCENT = 3;

export const DEFAULT_SHORT_TERM_STOP_LOSS_PERCENT = SHORT_TERM_STOP_LOSS_PERCENT;
export const DEFAULT_SHORT_TERM_TAKE_PROFIT_PERCENT = SHORT_TERM_TAKE_PROFIT_2_PERCENT;
